"""Add payment_method to Order and fix BillingAddress

Revision ID: 07ca6548e5e3
Revises: a5cb81a72ed7
Create Date: 2025-08-31 19:53:03.454807

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "07ca6548e5e3"
down_revision = "a5cb81a72ed7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("billing_address", schema=None) as batch_op:
        batch_op.alter_column(
            "firstname", existing_type=sa.VARCHAR(length=100), nullable=False
        )
        batch_op.alter_column(
            "lastname", existing_type=sa.VARCHAR(length=100), nullable=False
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_billing_address_order_id"), ["order_id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("billing_address", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.alter_column(
            "lastname", existing_type=sa.VARCHAR(length=100), nullable=True
        )
        batch_op.alter_column(
            "firstname", existing_type=sa.VARCHAR(length=100), nullable=True
        )

    # ### end Alembic commands ###
