"""Add quantity to OrderItem

Revision ID: 9e611649ffc9
Revises: 07ca6548e5e3
Create Date: 2025-08-31 20:07:28.987709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e611649ffc9'
down_revision = '07ca6548e5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commends auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commends ###


def downgrade():
    # ### commends auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commends ###
