"""Add BillingAddress table and relation to Order

Revision ID: b224ba0ffc54
Revises: 7acac89d9431
Create Date: 2025-08-31 19:25:51.789804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b224ba0ffc54'
down_revision = '7acac89d9431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commends auto generated by Alembic - please adjust! ###
    op.create_table('billing_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('apartment', sa.String(length=200), nullable=True),
    sa.Column('discord', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commends ###


def downgrade():
    # ### commends auto generated by Alembic - please adjust! ###
    op.drop_table('billing_address')
    # ### end Alembic commends ###
